apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cumulusairauths.cumulusair.com
spec:
  group: cumulusair.com
  names:
    kind: CumulusAirAuth
    listKind: CumulusAirAuthList
    plural: cumulusairauths
    singular: cumulusairauth
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
