apiVersion: v1
kind: Secret
metadata:
  name: cumulusairauth
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.metadata.name }} 
type: Opaque
data:
  UID: "{{ .Values.mariadb.uid }}"
  PASSWORD: "{{ .Values.mariadb.password }}"
  SECRET: "{{ .Values.mariadb.secret }}"